### ISSUE TITLE
My laptop's colorama package is not working

### ISSUE THREAD

**Issue by nspNSPnsp** [Lanzoor/LCP#1]
I just upgraded from 0.2 beta to 0.3 beta, and when I try to start the program, this error shows up:

`Starting inspection...
Python interpreter version requirement passed! (Required: 3.10~, Current: 3.12.3)
Recommended Windows version passed! (Recommended: Windows 11~, Current: 11)
Seems like you didn't properly install the required packages for this project.
Unfortunately, we can't automatically install the packages for you / use pyInstaller because it comes with a huge risk and might not be compatiable with a lot of OS's.
Please see if you are missing anything and follow everything in https://github.com/Lanzoor/LCP/blob/main/README.md !
Traceback (most recent call last):
  File "c:\Users\USER\Downloads\LCP-0.3-beta\LCP-0.3-beta\script.py", line 40, in <module>        
    from colorama import Fore, Style
ModuleNotFoundError: No module named 'colorama'`

And 2 seconds later, another error:

`During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\Users\USER\Downloads\LCP-0.3-beta\LCP-0.3-beta\script.py", line 46, in <module>        
    raise ForceQuitted("Program exited due to missing dependencies.")
ForceQuitted: Program exited due to missing dependencies.`

And when I try:

`pip install colorama`

This error shows up telling me I already have it:

`Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: colorama in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.4.6)  `

**Comment by Lanzoor** [comment]
The second error is supposed to happen if you're missing colorama, but weird. I will try to search what went wrong with the code.

**Comment by Lanzoor** [comment]
I've gotta go to school (hell), but will make sure to drop 0.4-beta soon and furthermore check the issue!

**Comment by Lanzoor** [comment]
Not an issue related to LCP / golbal scripts, therefore closing.
